<a href="https://colab.research.google.com/github/sanju-shivam/Machine-learning/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
# 1d array or vector
a= np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [7]:
# 2d array or matrix
b = np.array([[1,2,3],[1,2,3]])
print((b))

[[1 2 3]
 [1 2 3]]


In [8]:
# 3d array or tensor
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print((c))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
# np.one, np.zeros, np.random
# np.zeros([2,3])
# np.ones([2,3])
np.random.random((3,3))  # it generate value between 0 ot 1 but random

array([[0.5003986 , 0.92131387, 0.45150479],
       [0.02175421, 0.95512702, 0.58825346],
       [0.19957337, 0.22854627, 0.23994343]])